use std::error::Error;

pub fn current() -> Result<(), Box<dyn Error>> {
    Ok(())
}
